### ISSUE TITLE
Deploy custom hostname and SSL to slots

### ISSUE THREAD

**Issue by BevanG** [wearetriple/ados-extension-ssl-custom-domain#1]
Hi There, thanks very much for providing this extension which works well on a base Web Service. Are you able to also provide a way to deploy into slots?

If I put appservicename/slots/slotname into the App Service field the certificate uploads correctly. It's just the custom hostname it has a problem with.

I'll have a look at the code and see if I can change it as well.

**Comment by ThomasBleijendaal** [comment]
Hi,

I haven't looked into deploying into slots, but you're free to see if you can add support to it and open a PR.
I use this powershell script to test the extension locally:

```
Login-AzureRmAccount -SubscriptionId "guid"
$ResourceGroupName = "resourcegroup"
$AppServiceName = "appservice"
$CustomDomains = "example.com"
$CertificatePassword = "***"
$CertificateFileName = "cert.pfx"
$env:AGENT_TEMPDIRECTORY = "C:\pathtocert"
sslcustomdomain\sslcustomdomain.ps1 `
    -ResourceGroupName $ResourceGroupName `
    -AppServiceName $AppServiceName `
    -CustomDomains $CustomDomains `
    -CertificatePassword $CertificatePassword `
    -CertificateFileName $CertificateFileName
```

**Comment by BevanG** [comment]
Thanks for the quick reply. I've been able to provide a solution for this. Thankfully the Azure resource for a slot is appservicename/slotname

So an app service named "website" with a slot named "website-slot" is referred to as "website/website-slot". This meant I just needed a simple if ($AppserviceName -like "*/*") {} else {} a few times in your script and target "Microsoft.Web/sites/slots" as the Resource Type.

Would you be able to update your "sslcustomdomain.ps1" with this attached script and update the extension?

I'll run the task manually as a Powershell script for now.

[UploadCerttoWebAppSlot.txt](https://github.com/wearetriple/ados-extension-ssl-custom-domain/files/2671654/UploadCerttoWebAppSlot.txt)

**Comment by ThomasBleijendaal** [comment]
Thanks for the updated script. I'll test new code and update the extension somewhere this week, and close this issue when the update is ready.

**Comment by BevanG** [comment]
That's great, thanks very much. It would be worth adding a comment on the Task to mention if deploying to slot, use AppServicename/SlotName

Alternatively you can put a new field in the form with "Slot Name" and I can edit the Powershell script for you to allow for $SlotName

If you would like anything extra from me, please ask.

**Comment by ThomasBleijendaal** [comment]
@BevanG I have updated the extension, so you can add Slot Name as an extra parameter. It's currently verifying so it should be updated any time soon. You'll probably have to uninstall and reinstall the extension in your vsts since it does not auto-update that quickly.
