### ISSUE TITLE
Download Secure File output secureFilePath as input for CertificateFileName

### ISSUE THREAD

**Issue by rdeveen** [wearetriple/ados-extension-ssl-custom-domain#3]
When downloading the certificate to the build agent with the Download Secure File task, the [output variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops) of that task contains the location of the certificate file. This output variable can be used as input for the CertificateFileName input variable of this task. 

This [line ](https://github.com/wearetriple/ados-extension-ssl-custom-domain/blob/8927ab3680ebeda03d2a082d45bf88cc9c46e0a3/sslcustomdomain/sslcustomdomain.ps1#L31) adds the temp directory to the CertificateFileName with makes it impossible to use the output variable of the previous task with already contains the temp directory. 

There should be an check that if the CertificateFileName already contains the full directory path, the temp directory should not be added again.

**Comment by Bas-kolthof-triple** [comment]
Should be addressed by #6, if not, let me know.

**Comment by rdeveen** [comment]
I think we have a forward/backslash issue here. We use a Windows Build agent.

This is the important part of the log output:

```
##[section]Starting: Install SSL and Custom Domain

CertificateFileName
d:\A2\_work\_temp\STAR_***_nl.pfx

CertificateFilePath
d:\A2\_work\_temp/d:\A2\_work\_temp\STAR_***_nl.pfx

#[error]Certificate does not exist at path d:\A2\_work\_temp/d:\A2\_work\_temp\STAR_***_nl.pfx
```

**Comment by rdeveen** [comment]
@Bas-kolthof-triple can you have a look at this?

**Comment by Bas-kolthof-triple** [comment]
Sorry that it took so long, I put in a PR that should address your issue just now.

**Comment by rdeveen** [comment]
See #9

**Comment by rdeveen** [comment]
Thank you, it is working.
